services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev.cpu
    image: latextranscribe-backend
    ports:
      - 8080:8080
    command: ["supervisord", "-c", "supervisord.dev.conf"]
    develop:
      watch:
        - action: sync
          path: ./server
          target: /app
          ignore:
            - .venv/
            - .cache/
        - action: rebuild
          path: ./server/pyproject.toml
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: latextranscribe-frontend
    ports:
      - 8000:8000
    command: ["npm", "run", "dev"]
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json
