services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.cpu
    image: latextranscribe
    ports:
      - 8081:80
    command: ["gunicorn", "-w", "2", "app:app", "--bind", "0.0.0.0:80", "--reload", "--access-logfile", "'-'", "--log-level", "debug"]
    develop:
      watch:
        - action: sync
          path: ./server
          target: /app
          ignore:
            - .venv/
  frontend:
    build:
      context: ./frontend
      # https://docs.docker.com/reference/compose-file/build/#target
      target: dev
    image: latextranscribe-frontend
    ports:
      - 8080:5173
    command: ["npm", "run", "dev"]
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
