input_path: /Users/louis/Documents/project/research/giant/LatexTranscribe/input
output_path: /Users/louis/Documents/project/research/giant/LatexTranscribe/output
models:
  formula_detection:
    model_name: formula_detection_yolo
    model_path: models/MFD/YOLO/yolo_v8_ft.pt
    img_size: 1280
    conf_thres: 0.10
    iou_thres: 0.20
    batch_size: 1
    visualize: True
  layout_detection:
    model_name: layout_detection_layoutlmv3
    model_path: models/Layout/LayoutLMv3/model_final.pth
  formula_recognition:
    model_name: formula_recognition_unimernet
    cfg_path: configs/unimernet.yaml
    model_path: models/MFR/unimernet_base
    visualize: True
  table_recognition:
    model_name: table_parsing_struct_eqtable
    model_path: models/TabRec/StructEqTable
    max_new_tokens: 1024
    max_time: 30
    output_format: latex
    lmdeploy: False
    flash_atten: True